// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bank struct {
	ID       pgtype.UUID        `db:"id" json:"id"`
	First    string             `db:"first" json:"first"`
	Last     string             `db:"last" json:"last"`
	Email    string             `db:"email" json:"email"`
	Amount   pgtype.Numeric     `db:"amount" json:"amount"`
	Creation pgtype.Timestamptz `db:"creation" json:"creation"`
}
